### ISSUE TITLE
Need Guidance - Deploying Whisper JAX and Cloud Service Selection

### ISSUE THREAD

**Issue by xx77yy** [Dicklesworthstone/bulk_transcribe_youtube_videos_from_playlist#1]
**Issue:**
Hi everyone,

I hope you're doing well. 
**Challenge 1: Choosing a Cloud Service**
I'm new to deploying applications, and I'm uncertain about which cloud platform would be the most suitable for hosting Whisper JAX. Any recommendations or advice for someone starting out?

Your insights and expertise would be incredibly helpful. Looking forward to learning from the community!

Thank you,
Sky

**Comment by Dicklesworthstone** [comment]
Not sure what you are talking about-- this project doesn't use Whisper JAX. If you just want a hosting provider where you can get a cheap linux server to try stuff out on, I suggest Contabo or Hetzner.
