### ISSUE TITLE
HTTP Error 400: Bad Request trying to transcribe ANY video

### ISSUE THREAD

**Issue by jonathanlyon** [Dicklesworthstone/bulk_transcribe_youtube_videos_from_playlist#8]
I've tried everything I can to try and get this to work and I'm out of ideas now. I have tried different python versions and the same issue persists - **HTTP Error 400: Bad Request**.

system
  3.8.19
*** 3.12.4**

My system version is 3.9.6 and I'm on a mac-mini M1 and believed the 3020 urlib3 issue was to blame but despite trying different versions of python, I'm still getting the same error.

[https://github.com/urllib3/urllib3/issues/3020](https://github.com/urllib3/urllib3/issues/3020)

Any ideas?

Thanks

Jonathan

![Screenshot 2024-07-19 at 11 37 33 PM](https://github.com/user-attachments/assets/ed275e2f-00de-4fba-be07-26064e4434d5)

**Comment by jonathanlyon** [comment]
seems like it is the urllib3 issue, I just tried a different script and it failed with the same error:-

I have no idea how to fix this now and would welcome any ideas :-)

Thanks

Jonathan

![Screenshot 2024-07-20 at 12 58 15 AM](https://github.com/user-attachments/assets/838ac8b3-668e-419d-a91e-b3ba502e20eb)

**Comment by Dicklesworthstone** [comment]
Try using pyenv and python 3.12. Also past the source code and your error
message into chatgpt gpt-4o and it will solve it for you.

**Comment by Mungoid** [comment]
Ran into the same issue and I'm not sure if YT made some changes but i found using Pytubefix instead of Pytube seems to be working: https://pypi.org/project/pytubefix/

**Comment by Dicklesworthstone** [comment]
Ah yes I think you’re right, I will test and make that change, too. Thanks
for letting me know

**Comment by jonathanlyon** [comment]
awesome, thank you, I'm looking forward to trying it out, I appreciate your efforts!

Thanks

Jonathan

**Comment by Dicklesworthstone** [comment]
@Mungoid Can confirm that this fixes the problem, thank you!
